language: cpp
compiler: g++
os: linux
sudo: false
env:
  global:
  - CC=gcc-4.8
  - CXX=g++-4.8
  - CMAKE_URL=http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-i386.tar.gz
  - CMAKE_DIRNAME=cmake-3.1.0-Linux-i386

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libc6-i386

before_install:
  # Enforce whitespace guidelines
  - ./scripts/whitespace_check.sh

  # Enforce Leap Motion copyright notice
  - ./scripts/copyright_check.sh

  # Verify that our version numbers all line up
  - ./scripts/version_number_updated.sh

install:
  # CMake 3.1
  - curl $CMAKE_URL | tar xz

  # g++4.8.1
  - export CC=gcc-4.8
  - export CXX=g++-4.8

before_script:
  - export CPATH=/usr/include/c++/4.8:/usr/include/x86_64-linux-gnu/c++/4.8/:$CPATH
  - export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8:$LD_LIBRARY_PATH

script:
  # Build Autowriring, run unit tests, and install
  - $CMAKE_DIRNAME/bin/cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=~/autowiring/
  - make -j 4 || make
  - ctest --output-on-failure
  - make install
  - cpack || (cat _CPack_Packages/Linux/TGZ/InstallOutput.log; exit 3)
  - cd examples
  - ../$CMAKE_DIRNAME/bin/cmake . -DCMAKE_PREFIX_PATH:PATH=~
  - make


after_failure:
  - cat Testing/Temporary/LastTest.log 2> /dev/null
