language: cpp
compiler: g++
os: linux

before_install:
  # Enforce whitespace guidelines
  - ./scripts/whitespace_check.sh

  # Enforce Leap Motion copyright notice
  - ./scripts/copyright_check.sh

  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then 
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      && export CXX;
    fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then
      sudo add-apt-repository -y ppa:h-rayflood/llvm;
    fi

  - sudo apt-get remove gcc-4.6 g++-4.6 cmake
  - sudo apt-get -qq update

install:
  # CMake 3.0
  - sudo apt-get -qq install libc6-i386
    && wget http://www.cmake.org/files/v3.0/cmake-3.0.2-Linux-i386.tar.gz
    && tar -xzf cmake-3.0.2-Linux-i386.tar.gz
    && sudo cp -fR cmake-3.0.2-Linux-i386/* /usr

  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then 
      sudo apt-get install -qq  gcc-4.8 g++-4.8
      && export CXX="g++-4.8"
      && sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
      && sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++;
    fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then
      sudo apt-get install --allow-unauthenticated -qq clang-3.4
      && export CXX="clang++-3.4";
    fi

before_script:
  - export CPATH=/usr/include/c++/4.8:/usr/include/x86_64-linux-gnu/c++/4.8/:$CPATH
  - export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8:$LD_LIBRARY_PATH
  - cmake . -DCMAKE_BUILD_TYPE=Release

script:
  # Build Autowriring, run unit tests, and install
  - make -j 8 || make
  - make test
  - sudo make install

  # Package
  - sudo cpack . -D "TGZ"
  - sudo cpack . -D "DEB"

  # Build examples from installed Autowiring
  - cd examples 
    && cmake . -DUSE_LIBCXX=ON
    && make
    && cd ..

after_failure:
  - cat Testing/Temporary/LastTest.log 2> /dev/null
